FROM python:3.10

EXPOSE 8000

WORKDIR /app

# Install Poetry
ENV PATH="/opt/poetry/bin:$PATH"
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 \
    && poetry config virtualenvs.create false

COPY . .

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --no-dev ; fi" \
    && chmod +x /app/start.sh

ARG START_LOCAL=${START_LOCAL}
ARG HOST=${HOST}
ARG PORT=${PORT}

CMD ["sh", "-c", "/app/start.sh"]